version: "3.7"
services:
  mysql5.6:
    image: mysql:5.6
    restart: always
    ports:
      - "3356:3306"
    volumes:
      - "./dbdata_mysql5.6:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fxjs-orm-test
  mysql5.7:
    image: mysql:5.7
    restart: always
    ports:
      - "3357:3306"
    volumes:
      - "./dbdata_mysql5.7:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fxjs-orm-test
  mysql8.0:
    # options `--default-authentication-plugin` has been deprecated since mysql server 8.0.27
    # it works on mysql 8.0.29 still, but for robust, we specify the image as mysql:8.0.26
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3380:3306"
      - "3306:3306"
    volumes:
      - "./dbdata_mysql8.0:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fxjs-orm-test
  postgres14:
    image: postgres:14
    restart: always
    ports:
      - "5514:5432"
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=fxjs-orm-test
    # Uncomment this if you want to persist the data.
    volumes:
      - "./dbdata_pg14:/var/lib/postgresql/data"
  dm8:
    image: sizx/dm8
    restart: always
    ports:
      - "5236:5236"
    environment:
      - SYSDBA_PWD=123456789
      - PAGE_SIZE=32
      - CHARSET=1
      - LENGTH_IN_CHAR=1
      - CASE_SENSITIVE=0
  redis:
    image: 'redis:6.0'
    restart: always
    container_name: docker_redis
    volumes:
      - "./dbdata_redis6.0/data:/data"
      - "./dbdata_redis6.0/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./dbdata_redis6.0/logs:/logs"
    command:
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
  # mongodb:
  #   image: mongo:5.0
  #   ports:
  #     - "27017:27017"
  #     - "27050:27017"
  #   volumes:
  #     - ./dbdata_mongo5.0:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=
  #     - MONGO_INITDB_ROOT_PASSWORD=
volumes:
  db_data: null